### PR TITLE
Peer TLS not enabled after rolling update

### LINKED ISSUE #420: [BUG] Peer TLS not enabled after rolling update
**Describe the bug:**
Configuring `etcd.spec.etcd.peerUrlTLS` to activate TLS for peer communication **for an existing** etcd cluster will trigger a rolling update, i.e. all pods receive the required configuration and certificates. However, after the rolling update is finished, the peer communication does not properly work via TLS.

If TLS is enabled later, the `peer` address(es) in the cluster have to be changed which is done by `etcd-backup-restore`. After this change another restart is required which is currently not triggered. 

**Expected behavior:**
TLS communication works properly after changing the `etcd` resource.

**How To Reproduce (as minimally and precisely as possible):**
1. Create a multi-node `etcd` cluster w/o peer tls
2. Configure `etcd.spec.etcd.peerUrlTLS`
3. Observe that member pods don't start because of broken TLS communication.

### PR DESCRIPTION
**Pull request by unmarshall**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
For a single node etcd the peer URL is not TLS enabled. This causes an issue when the same etcd cluster has to be scaled up from 1 to 3. All the new etcd pods will try and reach the existing etcd member over TLS enabled peer URL and will get a response in HTTP which will get rejected. As a result all the new pods will go into `CrashLoopBackOff` and will never recover.

**Which issue(s) this PR fixes**:
Fixes #420 and #419

**Special notes for your reviewer**:
@timuthy  e2e tests are currently pending.
I have marked it currently as WIP as i have some unit tests to write for the sts component changes.
**Release note**:

```other operator
Enables etcd-druid to trigger restarts of the etcd pods when peer URL is TLS enabled.
```

### CODE REVIEW

**Comment by unmarshall** [comment]
unit tests added

File: pkg/component/etcd/statefulset/values.go [hunk 1]
```diff
@@ -124,4 +124,7 @@ type Values struct {
 	AutoCompactionRetention *string
 	// ConfigMapName is the name of the configmap that holds the ETCD config.
 	ConfigMapName string
+	// PeerUrlTLSAlreadyEnabled captures the existing enablement state for PeerUrl TLS. This will be used to compare the updated PeerUrlTLS
+	// to determine if action to update of PeerUrlTLS should be taken
+	PeerUrlTLSAlreadyEnabled *bool
```
Comment (timuthy) [inline pkg/component/etcd/statefulset/values.go:129]:
```suggestion
	StatusPeerUrlTLSEnabled *bool
```

Similar to `StatusReplicas`.

File: pkg/component/etcd/statefulset/statefulset.go [hunk 2]
```diff
@@ -71,19 +72,49 @@ func (c *component) Deploy(ctx context.Context) error {
...
+}
 
+func (c *component) getNumTimesToRecreateSts(sts *appsv1.StatefulSet) uint8 {
 	if sts.Generation > 1 && clusterScaledUpToMultiNode(c.values) && immutableFieldUpdate(sts, c.values) {
-		// Several immutable fields must be reset for the multi-node use-case.
-		deleteAndWait := gardenercomponent.OpDestroyAndWait(c)
-		if err := deleteAndWait.Destroy(ctx); err != nil {
+		return 1
+	} else if c.IsPeerUrlTLSChangedToEnabled() {
+		c.logger.Info("PeerUrl TLS has been enabled for etcd. To reflect this change etcd StatefulSet has to be re-created 2 times", "namespace", c.values.Namespace, "name", c.values.Name, "etcdUID", c.values.EtcdUID)
```
Comment (timuthy) [inline pkg/component/etcd/statefulset/statefulset.go:87]: Can you add a comment explaining why we need two restarts of all etcd pods?

**Review by timuthy — CHANGES_REQUESTED** [review]
Thanks for the changes. I added a few in-line comments.

File: controllers/etcd_controller.go [hunk 3]
```diff
@@ -686,21 +703,109 @@ func (r *EtcdReconciler) reconcileEtcd(ctx context.Context, logger logr.Logger,
...
+	cm := &corev1.ConfigMap{
+		ObjectMeta: metav1.ObjectMeta{
+			Name:      configMapNamespacedName.Name,
+			Namespace: configMapNamespacedName.Namespace,
+		},
+	}
+	err := r.Client.Get(ctx, configMapNamespacedName, cm)
+	switch {
+	case apierrors.IsNotFound(err):
+		return nil, nil
```
[the remark this answers is not in the document]
Comment (unmarshall) [reply controllers/etcd_controller.go:765]: It was an open point and my initial assumption was that if the config map is not there then i cannot assume any value for peerUrlTLS and therefore just return nil with the hope that it will get created. But I think this assumption is true in the gardener context and if we see usage of etcd-druid sans gardener then maybe it is better to just return the error and not ignore it.

File: controllers/etcd_controller.go [hunk 4]
```diff
@@ -686,21 +703,109 @@ func (r *EtcdReconciler) reconcileEtcd(ctx context.Context, logger logr.Logger,
...
+		peerUrlTLSEnabled: peerUrlTLSEnabled,
+		svcName:           &serviceValues.ClientServiceName,
+		sts:               sts,
+	}, err
+}
+
+// -------------------------- BEGIN: To be removed later --------------------------------------
+
+// capturePeerUrlTLSEnabledStatus captures the state of peer URL TLS enablement in etcd status.
+// It will fetch any existing ConfigMap and will derive the current state of PeerTLS enablement.
```
[the remark this answers is not in the document]
Comment (unmarshall) [reply controllers/etcd_controller.go:733]: Yes this was said in context to etcd so it was implicit. But may be it is better to make it explicit, removes mis-interpretations

File: controllers/etcd_controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (timuthy) [reply controllers/etcd_controller.go:765]: Got it, thank. Why don't we call `capturePeerUrlTLSEnabledStatus` later in the flow, i.e. right before the `StatefulSet` is deployed? We don't even need to consult the `ConfigMap`, but we can enhance the ConfigMap-Component as it already has the data in memory.

File: pkg/component/etcd/statefulset/statefulset.go (hunk 2 above)
Comment (unmarshall) [reply pkg/component/etcd/statefulset/statefulset.go:87]: Ok i will add it.

File: controllers/etcd_controller.go (hunk 3 above)
[the remark this answers is not in the document]
Comment (unmarshall) [reply controllers/etcd_controller.go:765]: The reason to always depend upon ConfigMap was that in the event of a crash, the in-memory state is not lost. Can you elaborate of what you have in mind?

**Comment by ishan16696** [comment]
Is this PR still in WIP state ?

**Comment by unmarshall** [comment]
> Is this PR still in WIP state @unmarshall ?

No. I have removed WIP from the subject line. Kindly review it critically.

File: pkg/component/etcd/lease/lease.go [hunk 5]
```diff
@@ -75,10 +82,23 @@ func (c *component) Destroy(ctx context.Context) error {
...
 
+func (c *component) GetPeerURLTLSEnabledStatus(ctx context.Context) (bool, error) {
+	tlsEnabledValues, err := c.getTLSEnabledAnnotationValues(ctx, c.values.EtcdName)
+	if err != nil {
+		return false, err
+	}
+	tlsEnabled := true
+	for _, v := range tlsEnabledValues {
+		tlsEnabled = tlsEnabled && v
+	}
```
Comment (ishan16696) [inline pkg/component/etcd/lease/lease.go:93]: AFAIU, you are checking the annotation in lease object of all etcd clusters  member , right but why ? 
Is there a reason behind it ?

**Comment by ishan16696** [comment]
`e2e-tests` have passed successfully  for this PR for storageProvider: Azure and AWS.

File: pkg/component/etcd/lease/lease.go (hunk 5 above)
Comment (unmarshall) [reply pkg/component/etcd/lease/lease.go:93]: The idea is to check if there is any member who still has a value of false. If the annotation is non-existent then it is ignored because its possible that the etcdbr has still not been able to set this annotation.
In the case the annotation is false then it requires 2 restarts in total.

Having said that, ideally this will return false when there is only a single-member etcd in case of gardener. Because today a single member etcd cluster is launched with a peer URL which does not have TLS enabled. When there is a multi-node cluster then it will be ensured from gardener that all new members will always have peer URL TLS enabled.

However, the above assumption is only relevant in case of gardener.

Comment (ishan16696) [reply pkg/component/etcd/lease/lease.go:93]: ok, got it

**Review by aaronfern — APPROVED** [review]
Looks good from my point of view
I've tested this out and all flows are working as expected
/lgtm

**Review by ishan16696 — APPROVED** [review]

**Review by timuthy — COMMENTED** [review]
Unfortunately, I can only have another look beginning next week. @aaronfern or @ishan16696 please feel free to merge if everything was tested successfully and the PR is in good shape, since I don't want to block the release.
