### PR TITLE
Use structured log messages

### LINKED ISSUE #524: [BUG] Fix logger time format for improved debugging and issue analysis and ensure structured logging is used.
**Describe the bug:**
Reference: https://sap-ti.slack.com/archives/C0177NLL8V9/p1676014983819069

**Time encoder:**
The date-time format used in etcd-druid makes it impossible to know the date and time. 
We have always used the default time encoder and recently a [PR#450](https://github.com/gardener/etcd-druid/pull/450) bumped up the controller-runtime version. We also see the following issue https://github.com/kubernetes-sigs/controller-runtime/pull/2029 which highlights that the default encoder is epoch time and the PR fixes that. Ideally we should not assume that the correct defaults are set and explicitly define the encoder while initialising the logger.

**Structured Logging and add context.**
Both logr and the underline zap provides for structured logging. Check if this is used consistently and correct anywhere it is not. Logs such as `Custodian controller reconciliation started` does not provide any benefit. Additional context should be provided.

**Expected behavior:**
Date and time should be clearly distinguished and visible for all log statements emitted. Structure logging should be used where parameters are passed.

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**How to categorize this PR?**

/area logging
/kind cleanup

**What this PR does / why we need it**:
Uses structured logging for all log messages. Also removes unused `corruptDBFile` function in e2e tests.

**Which issue(s) this PR fixes**:
Fixes #524 

**Special notes for your reviewer**:
/cc @unmarshall 

**Release note**:

```other operator
NONE
```

### CODE REVIEW

File: controllers/compaction/reconciler.go [hunk 1]
```diff
@@ -110,7 +110,7 @@ func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
 	fullLease := &coordinationv1.Lease{}
 
 	if err := r.Get(ctx, kutil.Key(etcd.Namespace, etcd.GetFullSnapshotLeaseName()), fullLease); err != nil {
-		logger.Info("Couldn't fetch full snap lease because: " + err.Error())
+		logger.Info("Couldn't fetch full snap lease", "error", err.Error())
```
Comment (unmarshall) [inline controllers/compaction/reconciler.go:113]:
```suggestion
		logger.Error(err, "Couldn't fetch full snap lease", "namespace", etcd.Namespace, "name", etcd.Name)
```

File: controllers/compaction/reconciler.go [hunk 2]
```diff
@@ -119,7 +119,7 @@ func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
 
 	deltaLease := &coordinationv1.Lease{}
 	if err := r.Get(ctx, kutil.Key(etcd.Namespace, etcd.GetDeltaSnapshotLeaseName()), deltaLease); err != nil {
-		logger.Info("Couldn't fetch delta snap lease because: " + err.Error())
+		logger.Info("Couldn't fetch delta snap lease", "error", err.Error())
```
Comment (unmarshall) [inline controllers/compaction/reconciler.go:122]: See above

File: controllers/compaction/reconciler.go [hunk 3]
```diff
@@ -343,7 +344,7 @@ func getCompactionJobVolumeMounts(etcd *druidv1alpha1.Etcd, logger logr.Logger)
 
 	provider, err := utils.StorageProviderFromInfraProvider(etcd.Spec.Backup.Store.Provider)
 	if err != nil {
-		logger.Info("Storage provider is not recognized. Compaction job will not mount any volume with provider specific credentials.")
+		logger.Info("Storage provider is not recognized. Compaction job will not mount any volume with provider specific credentials.", "error", err)
```
Comment (unmarshall) [inline controllers/compaction/reconciler.go:347]: see above

File: controllers/compaction/reconciler.go [hunk 4]
```diff
@@ -379,7 +380,7 @@ func getCompactionJobVolumes(etcd *druidv1alpha1.Etcd, logger logr.Logger) []v1.
 	storeValues := etcd.Spec.Backup.Store
 	provider, err := utils.StorageProviderFromInfraProvider(storeValues.Provider)
 	if err != nil {
-		logger.Info("Storage provider is not recognized. Compaction job will fail as no storage could be configured.")
+		logger.Info("Storage provider is not recognized. Compaction job will fail as no storage could be configured.", "error", err)
```
Comment (unmarshall) [inline controllers/compaction/reconciler.go:383]: see above

File: controllers/compaction/reconciler.go [hunk 5]
```diff
@@ -415,7 +416,7 @@ func getCompactionJobEnvVar(etcd *druidv1alpha1.Etcd, logger logr.Logger) []v1.E
 
 	provider, err := utils.StorageProviderFromInfraProvider(etcd.Spec.Backup.Store.Provider)
 	if err != nil {
-		logger.Info("Storage provider is not recognized. Compaction job will likely fail as there is no provider specific credentials.")
+		logger.Info("Storage provider is not recognized. Compaction job will likely fail as there is no provider specific credentials.", "error", err)
```
Comment (unmarshall) [inline controllers/compaction/reconciler.go:419]: see above

File: controllers/etcd/reconciler.go [hunk 6]
```diff
@@ -164,7 +164,7 @@ func (r *Reconciler) reconcile(ctx context.Context, etcd *druidv1alpha1.Etcd) (c
 
 	// Add Finalizers to Etcd
 	if finalizers := sets.NewString(etcd.Finalizers...); !finalizers.Has(common.FinalizerName) {
-		logger.Info("Adding finalizer")
+		logger.Info("Adding finalizer", "finalizerName", common.FinalizerName)
```
Comment (unmarshall) [inline controllers/etcd/reconciler.go:167]: add etcd name and namespace for which this is done

File: controllers/etcd/reconciler.go [hunk 7]
```diff
@@ -288,7 +288,7 @@ func (r *Reconciler) delete(ctx context.Context, etcd *druidv1alpha1.Etcd) (ctrl
 	}
 
 	if sets.NewString(etcd.Finalizers...).Has(common.FinalizerName) {
-		logger.Info("Removing finalizer")
+		logger.Info("Removing finalizer", "finalizerName", common.FinalizerName)
```
Comment (unmarshall) [inline controllers/etcd/reconciler.go:291]: add etcd name and namespace for which this is done

File: controllers/etcd/reconciler.go [hunk 8]
```diff
@@ -444,7 +444,7 @@ func (r *Reconciler) updateEtcdStatus(ctx context.Context, etcd *druidv1alpha1.E
 
 func (r *Reconciler) removeOperationAnnotation(ctx context.Context, logger logr.Logger, etcd *druidv1alpha1.Etcd) error {
 	if _, ok := etcd.Annotations[v1beta1constants.GardenerOperation]; ok {
-		logger.Info("Removing operation annotation")
+		logger.Info("Removing operation annotation", "annotation", v1beta1constants.GardenerOperation)
```
Comment (unmarshall) [inline controllers/etcd/reconciler.go:447]: add etcd name and namespace for which this is done

File: controllers/etcdcopybackupstask/reconciler.go [hunk 9]
```diff
@@ -99,7 +99,7 @@ func (r *Reconciler) reconcile(ctx context.Context, task *druidv1alpha1.EtcdCopy
 
 	// Ensure finalizer
 	if !controllerutil.ContainsFinalizer(task, common.FinalizerName) {
-		logger.V(1).Info("Adding finalizer")
+		logger.V(1).Info("Adding finalizer", "finalizerName", common.FinalizerName)
```
Comment (unmarshall) [inline controllers/etcdcopybackupstask/reconciler.go:102]: add etcd name and namespace for which this is done

File: controllers/etcdcopybackupstask/reconciler.go [hunk 10]
```diff
@@ -160,7 +160,7 @@ func (r *Reconciler) delete(ctx context.Context, task *druidv1alpha1.EtcdCopyBac
 
 	// Check finalizer
 	if !controllerutil.ContainsFinalizer(task, common.FinalizerName) {
-		logger.V(1).Info("Skipping as it does not have a finalizer")
+		logger.V(1).Info("Skipping since finalizer not present", "finalizerName", common.FinalizerName)
```
Comment (unmarshall) [inline controllers/etcdcopybackupstask/reconciler.go:163]: add etcd name and namespace for which this is done

File: controllers/secret/reconciler.go [hunk 11]
```diff
@@ -101,14 +101,14 @@ func addFinalizer(ctx context.Context, logger logr.Logger, k8sClient client.Clie
 	if finalizers := sets.NewString(secret.Finalizers...); finalizers.Has(common.FinalizerName) {
 		return nil
 	}
-	logger.Info("Adding finalizer")
+	logger.Info("Adding finalizer", "finalizerName", common.FinalizerName)
```
Comment (unmarshall) [inline controllers/secret/reconciler.go:104]: add etcd name and namespace for which this is done

File: controllers/secret/reconciler.go [hunk 12]
```diff
@@ -101,14 +101,14 @@ func addFinalizer(ctx context.Context, logger logr.Logger, k8sClient client.Clie
...
 	return client.IgnoreNotFound(controllerutils.AddFinalizers(ctx, k8sClient, secret, common.FinalizerName))
 }
 
 func removeFinalizer(ctx context.Context, logger logr.Logger, k8sClient client.Client, secret *corev1.Secret) error {
 	if finalizers := sets.NewString(secret.Finalizers...); !finalizers.Has(common.FinalizerName) {
 		return nil
 	}
-	logger.Info("Removing finalizer")
+	logger.Info("Removing finalizer", "finalizerName", common.FinalizerName)
```
Comment (unmarshall) [inline controllers/secret/reconciler.go:112]: add etcd name and namespace for which this is done

**Comment by shreyas-s-rao** [comment]
@unmarshall thanks for your review. I've made the changes as requested. PTAL

**Comment by unmarshall** [comment]
Can you also improve the logging for the following:

- [store.go](https://github.com/gardener/etcd-druid/blob/d3736357869bddbff3a210ab512a3cc0a0eb17da/pkg/utils/store.go#L67) - add namespace
- [statefulset.go](https://github.com/gardener/etcd-druid/blob/d3736357869bddbff3a210ab512a3cc0a0eb17da/pkg/component/etcd/statefulset/statefulset.go#L112) - add etcd name and namespace and possible the name of the pvc

**Comment by shreyas-s-rao** [comment]
@unmarshall done. PTAL

**Review by unmarshall — APPROVED** [review]
/ltgm
