### PR TITLE
Fix to allow etcd-druid to patch STS when there is only a change of mount-path even if all pods are not up and running

### LINKED ISSUE #908: v0.23.2 druid fails to reconcile an older versioned cluster when at least one etcd-member goes down prior to update of STS
**How to categorize this issue?**

/area control-plane
/kind bug

**What happened**:

v0.23.x version of etcd-druid changes the mount paths for TLS artifacts. This change is reflected in 2 places:
- ConfigMap
- StatefulSet - CLI args and Volume mount paths for TLS artifacts

Following are the changes to TLS volume paths:
| Container | Version < v0.23.x  | Version >= v0.23.x |
| ------------- | ------------- | ------------- |
|etcdbr | Name: `client-url-ca-etcd`<br/>MountPath: `/var/etcd/ssl/client/ca`  |  Name: `etcd-ca`<br/>MountPath:`/var/etcd/ssl/ca` | 
| etcdbr| Name:`client-url-etcd-server-tls`<br/>MountPath:`/var/etcd/ssl/client/server` | Name:`backup-restore-sever-tls`<br/>MountPath:`/var/etcdbr/ssl/server`  |
| etcdbr| Name:`client-url-etcd-client-tls`<br/>MountPath:`/var/etcd/ssl/client/client` | Name:`etcd-client-tls`<br/>MountPath:`/var/etcd/ssl/client` |
| etcd-wrapper| Name:`client-url-ca-etcd`<br/>MountPath:`/var/etcd/ssl/client/client` | Name:`etcd-ca`<br/>MountPath:`/var/etcd/ssl/ca` |
| etcd-wrapper| Name:`client-url-etcd-server-tls`<br/>`/var/etcd/ssl/client/client` | Name:`etcd-server-tls`<br/>MountPath:`/var/etcdbr/ssl/server` |
| etcd-wrapper| Name:`client-url-etcd-client-tls`<br/>MountPath:`/var/etcd/ssl/client/client` | Name:`etcd-client-tls`<br/>MountPath:`/var/etcdbr/ssl/client` |

Consider the following situation:
You have an etcd cluster which was setup using druid version v0.22.x this means that it will have the older volume mounts and also the same paths will also be reflected in the etcd ConfigMap.
Now when you upgrade druid to v0.23.y and annotate the `Etcd` resource with `gardener.cloud/operation=reconcile` then etcd-druid will first change the ConfigMap and update it with the new paths for TLS artifacts. Then it goes and attempts to update StatefulSet. Now imagine that just before the STS is updated one or more pods in the etcd-cluster go down. When they come up again, then it will now pick up the new ConfigMap and will attempt to start the etcd with the new TLS artifact paths. Since the volume mounts have not been changed yet (as this is only going to happen when STS is updated) the pod will never come up.
It will throw up the following error:
```
{"level":"fatal","ts":"2024-11-07T17:28:15.570Z","caller":"etcd-wrapper/main.go:58","msg":"error during start or run of etcd","error":"open /var/etcd/ssl/ca/bundle.crt: no such file or directory","stacktrace":"main.main\n\t/go/src/github.
com/gardener/etcd-wrapper/main.go:58\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```
When etcd-druid attempts to update the STS component it first checks if there are changes to TLS configuration. It is a bit conservative and errs on the side of caution by not updating the STS if all pods are not up and ready. So now this pod can no longer be started (without manual intervention) and etcd-druid does not proceed further in reconciling this Etcd resource.

**What you expected to happen**:

etcd-druid should be able to reconcile and update the etcd cluster even if a single pod is down.

**How to reproduce it (as minimally and precisely as possible)**:

- Deploy v0.22.x of druid and bring up a 3 member etcd cluster
- Upgrade druid to v0.23.y
- Annotate Etcd resource with `gardener.cloud/operation=reconcile` to force reconciliation of the etcd cluster
- Immediately bring down one of the etcd cluster nodes (ensuring that at least the ConfigMap has been updated but not STS)

### PR DESCRIPTION
**Pull request by unmarshall**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
The issue is described well in https://github.com/gardener/etcd-druid/issues/908. This PR allows etcd-druid to patch the StatefulSet allowing the unhealthy pod to come up eventually if what has changed is only TLS volume mount path.

> **NOTE:** If the TLS has been enabled for peer URL and is still not been reflected in StatefulSet then to ensure that the cluster  comes up post update of StatefulSet, it is essential that all members be up and running in a 3 member cluster. Therefore that  restriction will still be in place. What this PR does is relax this restriction in case only the mount paths have changed.
v0.23.x changes the mount paths for TLS volumes.

Additionally it also now adds an additional label to the etcd client and peer service to ensure that only statefulset pods are selected by it.

**Which issue(s) this PR fixes**:
Fixes #908 and #914

**Release note**:

```bugfix operator
Fixes etcd client and peer service label selector, ensuring that only Etcd statefulset pods are selected.
```
```bugfix operator
etcd controller now differentiates between TLS configuration change and peer TLS enablement. Only if peer TLS has been enabled and not yet reflected it will wait for all pods to come up else it will allow patching of statefulset.
```

### CODE REVIEW

File: internal/component/peerservice/peerservice.go [hunk 1]
```diff
@@ -111,7 +111,7 @@ func buildResource(etcd *druidv1alpha1.Etcd, svc *corev1.Service) {
 	svc.Spec.Type = corev1.ServiceTypeClusterIP
 	svc.Spec.ClusterIP = corev1.ClusterIPNone
 	svc.Spec.SessionAffinity = corev1.ServiceAffinityNone
-	svc.Spec.Selector = druidv1alpha1.GetDefaultLabels(etcd.ObjectMeta)
+	svc.Spec.Selector = utils.MergeMaps(druidv1alpha1.GetDefaultLabels(etcd.ObjectMeta), map[string]string{druidv1alpha1.LabelComponentKey: common.ComponentNameStatefulSet})
```
Comment (ishan16696) [inline internal/component/peerservice/peerservice.go:114]: should we add a comment here to remember why both label selector are required ?

File: internal/component/clientservice/clientservice.go [hunk 2]
```diff
@@ -111,7 +111,7 @@ func buildResource(etcd *druidv1alpha1.Etcd, svc *corev1.Service) {
 	svc.OwnerReferences = []metav1.OwnerReference{druidv1alpha1.GetAsOwnerReference(etcd.ObjectMeta)}
 	svc.Spec.Type = corev1.ServiceTypeClusterIP
 	svc.Spec.SessionAffinity = corev1.ServiceAffinityNone
-	svc.Spec.Selector = druidv1alpha1.GetDefaultLabels(etcd.ObjectMeta)
+	svc.Spec.Selector = utils.MergeMaps(druidv1alpha1.GetDefaultLabels(etcd.ObjectMeta), map[string]string{druidv1alpha1.LabelComponentKey: common.ComponentNameStatefulSet})
```
Comment (ishan16696) [inline internal/component/clientservice/clientservice.go:114]: same as above

File: internal/component/statefulset/statefulset.go [hunk 3]
```diff
@@ -309,10 +309,17 @@ func shouldRequeueForMultiNodeEtcdIfPodsNotReady(sts *appsv1.StatefulSet) bool {
 		sts.Status.ReadyReplicas < *sts.Spec.Replicas
 }
 
-func isStatefulSetTLSConfigInSync(etcd *druidv1alpha1.Etcd, sts *appsv1.StatefulSet) bool {
+func (r _resource) hasTLSEnablementForPeerURLReflectedOnSTS(etcd *druidv1alpha1.Etcd, existingSts *appsv1.StatefulSet) bool {
+	newEtcdWrapperPeerTLSVolMounts := getEtcdContainerPeerVolumeMounts(etcd)
+	containerPeerTLSVolMounts := utils.GetEtcdContainerPeerTLSVolumeMounts(existingSts)
```
Comment (ishan16696) [inline internal/component/statefulset/statefulset.go:314]:
```suggestion
	containerPeerURLTLSVolMounts := utils.GetEtcdContainerPeerURLTLSVolumeMounts(existingSts)
```
do you want to change the name as we discussed the PeerTLS is technically wrong name to say.

Comment (unmarshall) [reply internal/component/statefulset/statefulset.go:314]: `containerPeerTLSVolMounts` is semantically correct.

File: internal/component/peerservice/peerservice.go (hunk 1 above)
Comment (unmarshall) [reply internal/component/peerservice/peerservice.go:116]: addressed in 10733c791eec82f08b258f882e4eeb769b037d00

File: internal/component/peerservice/peerservice.go [hunk 4]
```diff
@@ -111,7 +111,9 @@ func buildResource(etcd *druidv1alpha1.Etcd, svc *corev1.Service) {
 	svc.Spec.Type = corev1.ServiceTypeClusterIP
 	svc.Spec.ClusterIP = corev1.ClusterIPNone
 	svc.Spec.SessionAffinity = corev1.ServiceAffinityNone
-	svc.Spec.Selector = druidv1alpha1.GetDefaultLabels(etcd.ObjectMeta)
+	// Peer service should only target StatefulSet pods. Default labels are going to be present on anything that is managed by etcd-druid and started for an etcd cluster.
+	// Therefore, only using this as a label selector can cause issues as we have already seen in https://github.com/gardener/etcd-druid/issues/914
```
Comment (ishan16696) [inline internal/component/peerservice/peerservice.go:115]:
```suggestion
	// Therefore, only using defaultLabels as a label selector can cause issues as we have already seen in https://github.com/gardener/etcd-druid/issues/914
```

File: internal/component/clientservice/clientservice.go [hunk 5]
```diff
@@ -111,7 +111,9 @@ func buildResource(etcd *druidv1alpha1.Etcd, svc *corev1.Service) {
 	svc.OwnerReferences = []metav1.OwnerReference{druidv1alpha1.GetAsOwnerReference(etcd.ObjectMeta)}
 	svc.Spec.Type = corev1.ServiceTypeClusterIP
 	svc.Spec.SessionAffinity = corev1.ServiceAffinityNone
-	svc.Spec.Selector = druidv1alpha1.GetDefaultLabels(etcd.ObjectMeta)
+	// Client service should only target StatefulSet pods. Default labels are going to be present on anything that is managed by etcd-druid and started for an etcd cluster.
+	// Therefore, only using this as a label selector can cause issues as we have already seen in https://github.com/gardener/etcd-druid/issues/914
```
Comment (ishan16696) [inline internal/component/clientservice/clientservice.go:115]:
```suggestion
	// Therefore, only using defaultLabels as a label selector can cause issues as we have already seen in https://github.com/gardener/etcd-druid/issues/914
```

File: internal/component/peerservice/peerservice.go (hunk 4 above)
Comment (unmarshall) [reply internal/component/peerservice/peerservice.go]: fixed in 26c5d28cab652dc5c7daac6240bf7fbe116881ae

File: internal/component/clientservice/clientservice.go (hunk 5 above)
Comment (unmarshall) [reply internal/component/clientservice/clientservice.go]: fixed in 26c5d28cab652dc5c7daac6240bf7fbe116881ae

**Comment by ishan16696** [comment]
I have mentioned the steps to reproduce the bug and to test the fix : https://github.com/gardener/etcd-druid/issues/908#issuecomment-2470043625

**Review by seshachalam-yv — APPROVED** [review]
/lgtm

**Comment by ishan16696** [comment]
I have also tested the compaction job fix:

Before the fix etcd compaction pod is also added to endpointslices due to label selector of svc.
```
$kubectl describe endpointslices.discovery.k8s.io etcd-main-client-qght6
Name:         etcd-main-client-qght6
....
Endpoints:
  - Addresses:  10.244.0.19
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/etcd-main-0
    NodeName:   kind-control-plane
    Zone:       <unset>
  - Addresses:  10.244.0.20
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/etcd-main-compactor-stvkj
    NodeName:   kind-control-plane
    Zone:       <unset>
Events:         <none>

$ kubectl describe endpointslices.discovery.k8s.io etcd-main-peer-cbc4h

Name:         etcd-main-peer-cbc4h
...
Endpoints:
  - Addresses:  10.244.0.19
    Conditions:
      Ready:    true
    Hostname:   etcd-main-0
    TargetRef:  Pod/etcd-main-0
    NodeName:   kind-control-plane
    Zone:       <unset>
  - Addresses:  10.244.0.20
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/etcd-main-compactor-stvkj
    NodeName:   kind-control-plane
    Zone:       <unset>
Events:         <none>
```

Then I deployed druid with this PR image and trigger the compaction pod, etcd compaction pod is not also added to endpointSlices as now services are selecting the only etcd statefulset pods.
```
NAME                          READY   STATUS    RESTARTS   AGE
etcd-main-0                   2/2     Running   0          9m16s
etcd-main-compactor-88zsb     1/1     Running   0          90s

k describe endpointslices.discovery.k8s.io etcd-main-client-qght6
Name:         etcd-main-client-qght6
...
Endpoints:
  - Addresses:  10.244.0.19
    Conditions:
      Ready:    true
    Hostname:   <unset>
    TargetRef:  Pod/etcd-main-0
    NodeName:   kind-control-plane
    Zone:       <unset>
Events:         <none>

k describe endpointslices.discovery.k8s.io etcd-main-peer-cbc4h
Name:         etcd-main-peer-cbc4h
...
Endpoints:
  - Addresses:  10.244.0.19
    Conditions:
      Ready:    true
    Hostname:   etcd-main-0
    TargetRef:  Pod/etcd-main-0
    NodeName:   kind-control-plane
    Zone:       <unset>
Events:         <none>
```

**Review by ishan16696 — APPROVED** [review]
LGTM!!
