### PR TITLE
Enhance BackupReady condition handling

### LINKED ISSUE #413: [Enhancement] Exceptions for `BackupReady` condition
**Feature (What you would like to be added):**
Today, `Etcd-Druid` maintains the `BackupReady` condition even for `etcd` resources that don't define a backup. Even though the `status` of this conditions remains `Unknown`, we should rather not maintain the condition at all to not cause any confusion.

```
status:
  conditions:
  - lastTransitionTime: "2022-07-28T05:48:24Z"
    lastUpdateTime: "2022-08-22T15:21:11Z"
    message: Cannot determine etcd backup status
    reason: Unknown
    status: Unknown
    type: BackupReady
```

Furthermore, we should correctly maintain the `BackupReady` condition when `etcd.spec.replicas: 0` is set (aka hibernation). Today, the conditions becomes `false`:

```
  - lastTransitionTime: "2022-07-28T05:48:24Z"
    lastUpdateTime: "2022-08-22T15:23:08Z"
    message: Stale snapshot leases. Not renewed in a long time
    reason: BackupFailed
    status: "False"
    type: BackupReady
```

### PR DESCRIPTION
**Pull request by aaronfern**
**How to categorize this PR?**

/area backup
/kind enhancement

**What this PR does / why we need it**:
This PR enhances the `BackupReady` condition handling to take into account cases where the backup section is not defined and in cases where the etcd statefulset is scaled down

**Which issue(s) this PR fixes**:
Fixes #413 

**Special notes for your reviewer**:

**Release note**:

```other operator
Enhance `BackupReady` condition to take into account statefulset being scaled down and the backup section not being defined
```

### CODE REVIEW

File: pkg/health/condition/check_backup_ready.go [hunk 1]
```diff
@@ -48,6 +49,34 @@ func (a *backupReadyCheck) Check(ctx context.Context, etcd druidv1alpha1.Etcd) R
 		message: "Cannot determine etcd backup status",
 	}
 
+	// Special case of etcd not being configured to take snapshots
+	// Do not add the BackupReady condition if backup is not configured
+	if etcd.Spec.Backup.Store == nil {
+		return nil
```
Comment (timuthy) [inline pkg/health/condition/check_backup_ready.go:55]: Can you double check if this also works when backups are disabled afterwards, i.e. it was enabled before? I assume that the Backup condition will still be present and we probably want to condition to be removed. WDYT?

File: pkg/health/condition/check_backup_ready.go [hunk 2]
```diff
@@ -48,6 +49,34 @@ func (a *backupReadyCheck) Check(ctx context.Context, etcd druidv1alpha1.Etcd) R
...
+			}
+		}
+
+		if bckpCond.Status == "" {
+			result.status = druidv1alpha1.ConditionUnknown
+		} else {
+			result.status = bckpCond.Status
+		}
+		result.reason = ConditionNotChecked
+		result.message = "Statefulset has been scaled down"
```
Comment (timuthy) [inline pkg/health/condition/check_backup_ready.go:76]:
```suggestion
		result.message = "etcd cluster has been scaled down"
```

**Review by timuthy — CHANGES_REQUESTED** [review]
Looks good in genera, thanks for the contribution 🙂

File: pkg/health/condition/check_backup_ready.go (hunk 1 above)
Comment (aaronfern) [reply pkg/health/condition/check_backup_ready.go:55]: Hmm, I checked this and it does not remove the condition in this case
Let me try and see if we can support this case

Comment (aaronfern) [reply pkg/health/condition/check_backup_ready.go:56]: Updated the builder function to not add any old conditions to the condition set
PTAL whenever possible

Comment (timuthy) [reply pkg/health/condition/check_backup_ready.go:56]: To be on the safe side, can you only not add old conditions for known types `ConditionTypeReady`, `ConditionTypeAllMembersReady` and `ConditionTypeBackupReady`?

Comment (aaronfern) [reply pkg/health/condition/check_backup_ready.go:56]: Updated to include this

File: pkg/health/condition/builder.go [hunk 3]
```diff
@@ -23,6 +23,13 @@ import (
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
+//
+var skipMergeConditions = map[druidv1alpha1.ConditionType]bool{
```
Comment (timuthy) [inline pkg/health/condition/builder.go:27]:
```suggestion
var skipMergeConditions = map[druidv1alpha1.ConditionType]struct{}{
```
Since the value doesn't matter.

**Review by timuthy — CHANGES_REQUESTED** [review]

File: pkg/health/condition/builder.go (hunk 3 above)
Comment (aaronfern) [reply pkg/health/condition/builder.go]: Thanks for pointing this out :) 
Updated

File: pkg/health/condition/builder.go [hunk 4]
```diff
@@ -23,6 +23,13 @@ import (
 	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 )
 
+//
```
Comment (ishan16696) [inline pkg/health/condition/builder.go:26]: do you want to add something like in comment for what `skipMergeConditions` is used

File: pkg/health/condition/check_backup_ready.go [hunk 5]
```diff
@@ -48,6 +50,34 @@ func (a *backupReadyCheck) Check(ctx context.Context, etcd druidv1alpha1.Etcd) R
 		message: "Cannot determine etcd backup status",
 	}
 
+	// Special case of etcd not being configured to take snapshots
+	// Do not add the BackupReady condition if backup is not configured
+	if etcd.Spec.Backup.Store == nil {
```
Comment (ishan16696) [inline pkg/health/condition/check_backup_ready.go:55]: Can you also add a case when `etcd.Spec.Backup.Store.Provider` is passed as empty string.

**Review by ishan16696 — CHANGES_REQUESTED** [review]

File: pkg/health/condition/check_backup_ready.go (hunk 5 above)
Comment (aaronfern) [reply pkg/health/condition/check_backup_ready.go]: Added

**Review by timuthy — APPROVED** [review]
/lgtm
Thanks for taking care 🙂

File: pkg/health/condition/check_backup_ready.go [hunk 6]
```diff
@@ -48,6 +50,12 @@ func (a *backupReadyCheck) Check(ctx context.Context, etcd druidv1alpha1.Etcd) R
 		message: "Cannot determine etcd backup status",
 	}
 
+	// Special case of etcd not being configured to take snapshots
+	// Do not add the BackupReady condition if backup is not configured
+	if etcd.Spec.Backup.Store == nil || etcd.Spec.Backup.Store.Provider == nil {
```
Comment (ishan16696) [inline pkg/health/condition/check_backup_ready.go:55]: Please add this condition as well.
```suggestion
	if etcd.Spec.Backup.Store == nil || etcd.Spec.Backup.Store.Provider == nil  || len(*etcd.Spec.Backup.Store.Provider)==0{
```

**Review by ishan16696 — CHANGES_REQUESTED** [review]

File: pkg/health/condition/check_backup_ready.go (hunk 6 above)
Comment (aaronfern) [reply pkg/health/condition/check_backup_ready.go]: Added
