### PR TITLE
Reconciles compaction job on job status change along with snapshot lease change

### LINKED ISSUE #685: [BUG] Make the metric metricsjobcurrent capture accurate job end time
**Describe the bug:**
Currently the metric `metricsjobcurrent` is updated only when the delta event threshold crosses the limit and the compaction-controller in druid tries to create a new job or follow up the old job. But ideally, the metric should be updated even when the delta events are successfully compacted and the job is successful.

**Expected behavior:**
After a compaction job is run successfully and the delta events are compacted in backup, metric `metricsjobcurrent` should be updated to mark the end of the currently running job correctly in the dashboard. We can watch on the running compaction job status and as soon as the job is successful, we can update the `metricsjobcurrent` in the reconciler.

**How To Reproduce (as minimally and precisely as possible):**
Compaction job dashboard does not show the graph for `metricsjobcurrent` with correct end time of any successfully run compaction job.

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by abdasgupta**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
This PR solves a bug due to which compaction job related metrics were not having exactly accurate values. This PR actually reconciles compaction job on job status changes along with the holder identity changes in snapshot leases.

**Which issue(s) this PR fixes**:
Fixes #685 

**Special notes for your reviewer**:

**Release note**:

```noteworthy operator
Compaction job now reconciles on Job Status changes along with the holder identity changes in snapshot leases.
```

### CODE REVIEW

File: controllers/compaction/reconciler.go [hunk 1]
```diff
@@ -107,12 +107,39 @@ func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
 
 	logger := r.logger.WithValues("etcd", kutil.Key(etcd.Namespace, etcd.Name).String())
 
+	// Update metrics for currently running compaction job, if any
+	job := &batchv1.Job{}
```
Comment (shreyas-s-rao) [inline controllers/compaction/reconciler.go:111]: Why are we fetching the job here and checking the status (active, succeeded, failed) when we're already doing it in `reconcileJob()`? This seems redundant.

The PR may be correcting the inaccuracy in metrics exported, but in the process introduces redundancies and inefficiency in the reconciliation loop. I would ask you to please take a more holistic approach for this PR - if done right, it can solve both #685 as well as #698, by correcting the reconciliation loop flow (`reconcileJob()` should be called even if the revision difference crosses the threshold, unlike how it is done today). Ideally, reconciliation loop logic should be sound, and only then metrics should be exposed based on the operations and status information from the job.

**Review by shreyas-s-rao — CHANGES_REQUESTED** [review]
@abdasgupta thanks for your PR. PTAL at the comment and incorporate it in the PR. Thanks

File: controllers/compaction/reconciler.go (hunk 1 above)
Comment (abdasgupta) [reply controllers/compaction/reconciler.go:111]: We are checking the job status here because `reconcileJob()` is only called when the revision difference crosses the threshold. If the Job status is active, it also don't check the revision difference unnecessarily.

I don't understand what do you mean by `reconcileJob() should be called even if the revision difference crosses the threshold, unlike how it is done today` ! Currently, reconcileJob() is called upon revision difference crossing the threshold ..

What do you mean by holistic approach? You can point out which case is not handled in https://github.com/gardener/etcd-druid/issues/685 and https://github.com/gardener/etcd-druid/issues/698. I will add the case in this PR, if not added already.

Comment (shreyas-s-rao) [reply controllers/compaction/reconciler.go:111]: > We are checking the job status here because reconcileJob() is only called when the revision difference crosses the threshold. If the Job status is active, it also don't check the revision difference unnecessarily

This is exactly what needs to be changed. reconcileJob() needs to run irrespective of the difference in revisions. Meaning, the revision difference needs to be checked within reconcileJob(), which then determines whether to deploy a new job or not. But the check for the currently running job needs to happen irrespective of the revision check.

```code
reconcile() {
  ...
  reconcileJob()
}

reconcileJob() {
  getJob()
  if job exists {
    checkRunningJobStatus()
    updateJobStatusMetrics()
    if jobStatus == Running {
      return
    }
    if jobStatus == Succeeded || jobStatus == Failed {
      deleteJob()
    }
  }

  if deltaSnapRev - fullSnapRev > threshold {
    deployJob()
  }
}
```

This ensures that the reconciliation loop logic is sound, and also takes care of metrics being correctly exported.

Comment (abdasgupta) [reply controllers/compaction/reconciler.go:111]: Okay. Now I understand why do you think it's redundancy !

See, deployJob() can also fail instantly (for some reason). That's why we need to check job status even after deployJob() so that the controller is not run again from start. Only redundant check for  `job` is in line number 195. I think that is required after fetching leases and checking diff. One extra job status check won't be too much.

Otherwise , it is just moving codes from one block to other.

Comment (shreyas-s-rao) [reply controllers/compaction/reconciler.go:111]: > deployJob() can also fail instantly (for some reason)

For what reason exactly? And why would that have any effect on checking the job status?

> That's why we need to check job status even after deployJob() so that the controller is not run again from start

Once the reconciler deploys the job, it must requeue and exit, so that in the next reconciliation it can again check the job status and take appropriate actions. 

> One extra job status check won't be too much

It's not about whether it's too much. Even though the network impact of this may me minimal, the fact that the reconciler checks the same job status twice seems unnecessary to me, when in fact we can simplify the reconciliation flow logic to ensure that the job status is fetched irrespective of the revision threshold breach, and deploy a new job only if the threshold is breached and a job is not already currently running. I think this is a valid ask.

Comment (abdasgupta) [reply controllers/compaction/reconciler.go:111]: I tested repeatedly and after facing various error conditions under various circumstances , I decided this flow. I can't list them now as I don't remember all of them. What you suggesting is movement of code block from one place to another. I had my rationale and I tried to save a few loop reconciliation. But one or two redundant check of job status won't do any harm, specially when the job status comes from informer cache. Current flow goes like this:

1. In the Reconciler, a job is first checked for status. If it's succeeded, a delete call is issued on job.
2. The flow then enters to fetching leases and check the diff between leases.  Ideally, for most cases, when the reconciler is called upon status change of job for succeeded, diff check would not cross threshold because the delta events are just compacted. But, there might be some busy cluster where a job status change to successful and diff threshold cross may happen simultaneously.
3. Then we need to check if the job is really deleted or not and so we need the "redundant" job check of line number 195.
4. After the `createCompactionJob` call, I am no more issuing `Get` call on job, other than while deleting.
5. You may think line number 248 is redundant but I placed that for a reason. This line will only execute when a job is instantaneously succeeded, may be if there is no full snapshot in the storage at all or may be for some unknown reason which we should always be prepared for in a distributed system.
6. Action upon `job.Status.Failed` is executing only once, it's not redundant.

As I said, I won't feel confident if I need to change the flow that I wrote because I came to it after lots of testing in real scenarios upon various favourable and erroneous conditions. But if you just wish to move the codes from line number 110 inside the function `reconcileJob()`, that I can do. Do you wish that?

Comment (shreyas-s-rao) [reply controllers/compaction/reconciler.go:111]: > What you suggesting is movement of code block from one place to another

Not really. I suggested not adding the code block in this PR as it already exists in the code, within `reconcileJob()` method. I simply suggested calling `reconcileJob()` irrespective of the revision threshold breach, because reconciliation of a job is not just about deploying the job, but also fetching the status of the job and deleting the job, and these tasks need to performed irrespective of whether the revision threshold has been breached or not. Only the task of deploying a new job should be dependent on the revision threshold breach.

regarding the flow, I would request a second opinion from @unmarshall , because to me the flow you mentioned still seems to be repeated certain code like getJob() and checkStatus() partially and deleteJob(), and seems to be trying to handle specific corner cases, rather than being generic enough to work for any case.

/needs second-opinion
/assign @unmarshall

File: controllers/predicate/predicate.go [hunk 2]
```diff
@@ -179,8 +149,9 @@ func EtcdReconciliationFinished(ignoreOperationAnnotation bool) predicate.Predic
 	}
 }
 
-// IsSnapshotLease is a predicate that is `true` if the passed lease object is a snapshot lease.
-func IsSnapshotLease() predicate.Predicate {
+// SnapshotLeaseChanged is a predicate that is `true` if the passed lease object is a snapshot lease and if the lease
+// object's holderIdentity is updated.
+func SnapshotLeaseChanged() predicate.Predicate {
```
Comment (unmarshall) [inline controllers/predicate/predicate.go:154]: The lease holder identity currently holds the revision number. What you compare is only the revision. Why not just name it - `SnapshotRevisionChanged` which is semantically correct name for the function?

File: controllers/predicate/predicate.go [hunk 3]
```diff
@@ -205,3 +189,33 @@ func IsSnapshotLease() predicate.Predicate {
 		},
 	}
 }
+
+// JobStatusChanged is a predicate that is `true` if the status of a job changes.
+func JobStatusChanged() predicate.Predicate {
```
Comment (unmarshall) [inline controllers/predicate/predicate.go:194]: Why is this predicate required?

File: controllers/predicate/predicate_test.go [hunk 4]
```diff
@@ -114,13 +115,99 @@ var _ = Describe("Druid Predicate", func() {
 		var pred predicate.Predicate
 
 		JustBeforeEach(func() {
-			pred = LeaseHolderIdentityChange()
+			pred = SnapshotLeaseChanged()
```
Comment (unmarshall) [inline controllers/predicate/predicate_test.go:118]: Should be renamed to `SnapshotRevisionChanged`

File: controllers/predicate/predicate.go [hunk 5]
```diff
@@ -190,12 +161,25 @@ func IsSnapshotLease() predicate.Predicate {
...
+
 	return predicate.Funcs{
 		CreateFunc: func(event event.CreateEvent) bool {
 			return isSnapshotLease(event.Object)
 		},
 		UpdateFunc: func(event event.UpdateEvent) bool {
-			return isSnapshotLease(event.ObjectNew)
+			return isSnapshotLease(event.ObjectNew) && holderIdentityChange(event.ObjectOld, event.ObjectNew)
 		},
 		GenericFunc: func(event event.GenericEvent) bool {
```
Comment (unmarshall) [inline controllers/predicate/predicate.go:184]: Why do you need to return true for `GenericFunc`? You do not do that in `JobStatusChanged` predicate.
Also as per the definition of `GenericEvent` I do not see why a `true` should ever be returned.
Refer: https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.16.3/pkg/event#GenericEvent
Currently we do not define any `Source` which generates events of this type. Please adjust the unit tests as well.

File: controllers/predicate/predicate.go [hunk 6]
```diff
@@ -205,3 +189,33 @@ func IsSnapshotLease() predicate.Predicate {
 		},
```
Comment (unmarshall) [inline controllers/predicate/predicate.go:189]: Why do we need to react to delete event of a snapshot lease?

File: controllers/compaction/reconciler.go [hunk 7]
```diff
@@ -107,12 +107,39 @@ func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
...
+	if job != nil && job.Name != "" {
+		// Check if there is one active job or not
+		if job.Status.Active > 0 {
+			metricJobsCurrent.With(prometheus.Labels{druidmetrics.EtcdNamespace: etcd.Namespace}).Set(1)
+			// Don't need to requeue if the job is currently running
+			return ctrl.Result{}, nil
+		}
+
+		// Delete job if the job succeeded
+		if job.Status.Succeeded > 0 {
```
[the remark this answers is not in the document]
Comment (abdasgupta) [reply controllers/compaction/reconciler.go:126]: I think we really need a call to clarify the doubts.. I deliberately left failed situation unattended here

File: controllers/predicate/predicate.go (hunk 2 above)
Comment (abdasgupta) [reply controllers/predicate/predicate.go:154]: I think it is easier for anyone going through the code for the first time to understand that this function is dealing with Snapshot leases if we name it as `SnapshotLeaseChanged` .. if we name it `SnapshotRevisionChanged`, the person needs to understand quite a lot about backup-restore internals.

File: controllers/predicate/predicate.go (hunk 3 above)
Comment (abdasgupta) [reply controllers/predicate/predicate.go:194]: To trigger the reconciler when a job status is changed

File: controllers/predicate/predicate.go (hunk 5 above)
Comment (abdasgupta) [reply controllers/predicate/predicate.go:184]: Yes.. We can return false here

File: controllers/predicate/predicate.go (hunk 6 above)
Comment (abdasgupta) [reply controllers/predicate/predicate.go:189]: Is it not a good idea to check the revision diff for one last time and save snapshot using compaction?

File: controllers/predicate/predicate.go (hunk 2 above)
Comment (unmarshall) [reply controllers/predicate/predicate.go:154]: Well if someone is looking at etcd druid code base then first confusion point will be why do you even need a lease for a full and delta snapshot. Second confusing point will be what is this weird looking number mean when i look at the holderIdentity which is meant to hold something completely different. 

So from your own arguments it now becomes very clear to me when the predicate is named as `SnapshotRevisionChanged`. Any code reader would then realize that this predicate will check that the snapshot (full or delta) revision has changed and how it checks is the implementation detail. When he/she looks at how its done then they will come to realize that the holderIdentity holds the revision.

File: controllers/predicate/predicate.go (hunk 6 above)
Comment (unmarshall) [reply controllers/predicate/predicate.go:189]: In which even will a lease be deleted?

File: controllers/predicate/predicate.go (hunk 3 above)
Comment (unmarshall) [reply controllers/predicate/predicate.go:194]: When a Job is created then a re-queue is already done by the compaction reconciler. There is only one case which is etcd-druid restarts after spawning a Job. In that case also it will still get an event for the Job. Previously this predicate was not there, therefore my question on why is it required now

Comment (abdasgupta) [reply controllers/predicate/predicate.go:194]: Mainly to update the job related metrics correctly

File: controllers/compaction/reconciler.go (hunk 1 above)
Comment (abdasgupta) [reply controllers/compaction/reconciler.go:111]: I made the changes

File: controllers/predicate/predicate_test.go (hunk 4 above)
Comment (abdasgupta) [reply controllers/predicate/predicate_test.go]: Done

File: controllers/predicate/predicate.go (hunk 5 above)
Comment (abdasgupta) [reply controllers/predicate/predicate.go:184]: Done

File: controllers/predicate/predicate.go (hunk 6 above)
Comment (abdasgupta) [reply controllers/predicate/predicate.go:189]: added changes to not react to delete event

File: controllers/predicate/predicate.go (hunk 3 above)
Comment (abdasgupta) [reply controllers/predicate/predicate.go:194]: We discussed this in the meeting on why do we need it

File: controllers/predicate/predicate.go (hunk 2 above)
Comment (abdasgupta) [reply controllers/predicate/predicate.go]: Renamed

File: controllers/compaction/reconciler.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (abdasgupta) [reply controllers/compaction/reconciler.go:133]: I made the changes after an offline meeting where we decided that we exploit the reconciler to reconcile again in case of some immediate error just after creation of the job by the controller.

**Review by shreyas-s-rao — APPROVED** [review]
@abdasgupta thanks a lot for making the requested changes.
/lgtm

File: controllers/compaction/reconciler.go [hunk 8]
```diff
@@ -96,23 +96,78 @@ func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
...
+	logger := r.logger.WithValues("etcd", kutil.Key(etcd.Namespace, etcd.Name).String())
+
+	return r.reconcileJob(ctx, logger, etcd)
+}
+
+func (r *Reconciler) reconcileJob(ctx context.Context, logger logr.Logger, etcd *druidv1alpha1.Etcd) (ctrl.Result, error) {
+	// Update metrics for currently running compaction job, if any
+	job := &batchv1.Job{}
+	err := r.Get(ctx, types.NamespacedName{Name: etcd.GetCompactionJobName(), Namespace: etcd.Namespace}, job)
+	if err != nil {
```
Comment (unmarshall) [inline controllers/compaction/reconciler.go:113]: We are treating NotFound error and other errors as same. If there is an error getting a Job should we not re-queue instead of just logging it? In case it is not found then we move ahead.

Comment (abdasgupta) [reply controllers/compaction/reconciler.go]: Made the change

File: controllers/compaction/reconciler.go [hunk 9]
```diff
@@ -96,23 +96,84 @@ func (r *Reconciler) Reconcile(ctx context.Context, req ctrl.Request) (ctrl.Resu
...
+
+	return r.reconcileJob(ctx, logger, etcd)
+}
+
+func (r *Reconciler) reconcileJob(ctx context.Context, logger logr.Logger, etcd *druidv1alpha1.Etcd) (ctrl.Result, error) {
+	// Update metrics for currently running compaction job, if any
+	job := &batchv1.Job{}
+	if err := r.Get(ctx, types.NamespacedName{Name: etcd.GetCompactionJobName(), Namespace: etcd.Namespace}, job); err != nil {
+		if errors.IsNotFound(err) {
+			logger.Info("Currently, no compaction job is running")
```
Comment (unmarshall) [inline controllers/compaction/reconciler.go:114]: Can you please improve this log a bit by also logging the namespace and job name? Since druid runs for multiple etcd clusters, this log will not be very useful without additional information.

Comment (abdasgupta) [reply controllers/compaction/reconciler.go]: Done. Though we shouldn't print name of the job when there is no job running.

Comment (shreyas-s-rao) [reply controllers/compaction/reconciler.go]: I think namespace and etcd name should be sufficient, and rather necessary to identify which job does not exist according to the log. It's easier to simply add a `logger.WithValues()` at the beginning of reconciliation, so that all logs already have the etcd name and namespace, and the same logger is passed around within the reconciler.

**Review by unmarshall — APPROVED** [review]
/lgtm
