### PR TITLE
Fix reconciliation predicates.

### LINKED ISSUE #196: [BUG] Fix reconciliation predicates to fully comply with gardener extension contract
**Describe the bug:**
The main controller reconciles changes to `Etcd` resource `spec` even if `gardener.cloud/reconcile` annotation is not added. This is against the [gardener extension contract](https://github.com/gardener/gardener/blob/master/docs/extensions/reconcile-trigger.md).

**Expected behavior:**
The main controller should use the predicates in such a way that changes to the `Etcd` resource `spec` are reconciled only when the resource is also annotated appropriately. For example, see [here](https://github.com/gardener/gardener/blob/609107f2b19584315cc639b52668f73820dfc44a/extensions/pkg/controller/backupbucket/controller.go#L60-L72).

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID : v0.5.2
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by amshuman-kr**
**How to categorize this PR?**

/area control-plane
/kind bug

**What this PR does / why we need it**:
If operation annotation is to be honoured, the reconciliation predicates now match only if either operation annotation is present, or last operation didn't succeed or if the resource is undergoing deletion. No other change (if not accompanied by any of these conditions) will trigger reconciliation.

**Which issue(s) this PR fixes**:
Fixes #196 

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
If operation annotation is to be honoured, the reconciliation predicates now match only if either operation annotation is present, or last operation didn't succeed or if the resource is undergoing deletion. No other change (if not accompanied by any of these conditions) will trigger reconciliation.
```

### CODE REVIEW

File: pkg/predicate/predicate_test.go [hunk 1]
```diff
@@ -104,172 +104,126 @@ var _ = Describe("Druid Predicate", func() {
...
-							Annotations: map[string]string{
-								v1beta1constants.GardenerOperation: v1beta1constants.GardenerOperationReconcile,
-							},
-						},
-					}
-				})
-
-				It("should return false", func() {
-					predicate := HasOperationAnnotation()
+			It("should return false", func() {
```
Comment (shreyas-s-rao) [inline pkg/predicate/predicate_test.go:178]: Typo: `should return true`?

File: pkg/predicate/predicate_test.go [hunk 2]
```diff
@@ -104,172 +104,126 @@ var _ = Describe("Druid Predicate", func() {
...
 						},
-					}
-				})
+					},
+				}
+			})
 
-				It("should return false", func() {
-					predicate := HasOperationAnnotation()
+			It("should return false", func() {
```
Comment (shreyas-s-rao) [inline pkg/predicate/predicate_test.go:220]: Same as above

File: pkg/predicate/predicate_test.go [hunk 3]
```diff
@@ -104,172 +104,126 @@ var _ = Describe("Druid Predicate", func() {
...
-		Describe("#OR", func() {
-			Context("when has no operation annotation", func() {
-				BeforeEach(func() {
-					obj = &druidv1alpha1.Etcd{
-						ObjectMeta: metav1.ObjectMeta{
-							Annotations: make(map[string]string),
-						},
-					}
-				})
+	Describe("#OR", func() {
```
Comment (shreyas-s-rao) [inline pkg/predicate/predicate_test.go:189]: I did not understand the use of this `Describe` block, since it's the same as the one above (`#HasOperationAnnotation`). Or am I missing something here?

**Review by shreyas-s-rao — CHANGES_REQUESTED** [review]
@amshuman-kr Thanks a lot for the changes to the predicates and the addition of tests as well! I have a few questions. Please address them.

File: pkg/predicate/predicate_test.go (hunk 3 above)
Comment (amshuman-kr) [reply pkg/predicate/predicate_test.go:189]: You are right. This was an existing section and I did not pay attention to the fact that it was identical to the other section.

**Comment by amshuman-kr** [comment]
Thanks for the review @shreyas-s-rao! I have addressed your comments. Can you PTAL?

File: pkg/predicate/predicate_test.go [hunk 4]
```diff
@@ -94,182 +100,185 @@ var _ = Describe("Druid Predicate", func() {
...
+		Context("when has neither operation annotation nor last error", func() {
+			BeforeEach(func() {
+				obj = &druidv1alpha1.Etcd{
+					ObjectMeta: metav1.ObjectMeta{
+						Annotations: make(map[string]string),
+					},
+				}
+			})
+
+			It("should return true", func() {
```
Comment (shreyas-s-rao) [inline pkg/predicate/predicate_test.go:216]: @amshuman-kr Thanks for making the changes and the rebase too! Just one small typo here to fix, otherwise LGTM

Comment (amshuman-kr) [reply pkg/predicate/predicate_test.go:216]: 😅

**Comment by amshuman-kr** [comment]
@shreyas-s-rao I have addressed your comments. Can you PTAL?

**Review by shreyas-s-rao — APPROVED** [review]
@amshuman-kr Thanks for making the requested changes. LGTM
