### PR TITLE
Stop watching leases for custodian controller

### LINKED ISSUE #683: [BUG] Custodian controller does not honour `SyncPeriod` and updates etcd status too frequently
**Describe the bug:**
We observed an instance of custodian controller not honouring the `SyncPeriod` (set to `30s` by default) after a successful reconciliation and updates etcd status too frequently, ie every ~1-4 seconds. This is unacceptable due to the following reasons:
1. Too many API calls to the kube-apiserver
2. It does not allow etcd controller to make update calls to the etcd status to update reconciliation-derived status fields, ie `observedGeneration` and `lastError`, although actual reconciliation succeeded. This reflects wrong status of the etcd, since the etcd is actually healthy but the `observedGeneration` has not been updated.

**Expected behavior:**
Custodian controller should honour the provided `SyncPeriod` value and requeue events only upon statefulset status change or `SyncPeriod` seconds after a successful reconciliation, or immediately after a failed reconciliation.

**How To Reproduce (as minimally and precisely as possible):**

**Logs:**
```
k get etcd etcd-main -w -o=custom-columns=Cond0:.status.conditions[0].lastUpdateTime,Cond1:.status.conditions[1].lastUpdateTime,Cond2:.status.conditions[2].lastUpdateTime
Cond0                  Cond1                  Cond2
2023-09-27T09:44:08Z   2023-09-27T09:44:08Z   2023-09-27T09:44:08Z
2023-09-27T09:44:12Z   2023-09-27T09:44:12Z   2023-09-27T09:44:12Z
2023-09-27T09:44:16Z   2023-09-27T09:44:16Z   2023-09-27T09:44:16Z
2023-09-27T09:44:19Z   2023-09-27T09:44:19Z   2023-09-27T09:44:19Z
2023-09-27T09:44:23Z   2023-09-27T09:44:23Z   2023-09-27T09:44:23Z
2023-09-27T09:44:26Z   2023-09-27T09:44:26Z   2023-09-27T09:44:26Z
2023-09-27T09:44:29Z   2023-09-27T09:44:29Z   2023-09-27T09:44:29Z
2023-09-27T09:44:33Z   2023-09-27T09:44:33Z   2023-09-27T09:44:33Z
2023-09-27T09:44:34Z   2023-09-27T09:44:34Z   2023-09-27T09:44:34Z
2023-09-27T09:44:36Z   2023-09-27T09:44:36Z   2023-09-27T09:44:36Z
2023-09-27T09:44:37Z   2023-09-27T09:44:37Z   2023-09-27T09:44:37Z
2023-09-27T09:44:40Z   2023-09-27T09:44:40Z   2023-09-27T09:44:40Z
2023-09-27T09:44:44Z   2023-09-27T09:44:44Z   2023-09-27T09:44:44Z
2023-09-27T09:44:48Z   2023-09-27T09:44:48Z   2023-09-27T09:44:48Z
2023-09-27T09:44:50Z   2023-09-27T09:44:50Z   2023-09-27T09:44:50Z
2023-09-27T09:44:55Z   2023-09-27T09:44:55Z   2023-09-27T09:44:55Z
2023-09-27T09:44:58Z   2023-09-27T09:44:58Z   2023-09-27T09:44:58Z
2023-09-27T09:45:01Z   2023-09-27T09:45:01Z   2023-09-27T09:45:01Z
2023-09-27T09:45:05Z   2023-09-27T09:45:05Z   2023-09-27T09:45:05Z
2023-09-27T09:45:07Z   2023-09-27T09:45:07Z   2023-09-27T09:45:07Z
2023-09-27T09:45:09Z   2023-09-27T09:45:09Z   2023-09-27T09:45:09Z
2023-09-27T09:45:11Z   2023-09-27T09:45:11Z   2023-09-27T09:45:11Z
2023-09-27T09:45:16Z   2023-09-27T09:45:16Z   2023-09-27T09:45:16Z
2023-09-27T09:45:19Z   2023-09-27T09:45:19Z   2023-09-27T09:45:19Z
2023-09-27T09:45:22Z   2023-09-27T09:45:22Z   2023-09-27T09:45:22Z
2023-09-27T09:45:26Z   2023-09-27T09:45:26Z   2023-09-27T09:45:26Z
2023-09-27T09:45:30Z   2023-09-27T09:45:30Z   2023-09-27T09:45:30Z
2023-09-27T09:45:33Z   2023-09-27T09:45:33Z   2023-09-27T09:45:33Z
2023-09-27T09:45:37Z   2023-09-27T09:45:37Z   2023-09-27T09:45:37Z
2023-09-27T09:45:38Z   2023-09-27T09:45:38Z   2023-09-27T09:45:38Z
2023-09-27T09:45:40Z   2023-09-27T09:45:40Z   2023-09-27T09:45:40Z
2023-09-27T09:45:43Z   2023-09-27T09:45:43Z   2023-09-27T09:45:43Z
2023-09-27T09:45:48Z   2023-09-27T09:45:48Z   2023-09-27T09:45:48Z
2023-09-27T09:45:51Z   2023-09-27T09:45:51Z   2023-09-27T09:45:51Z
2023-09-27T09:45:54Z   2023-09-27T09:45:54Z   2023-09-27T09:45:54Z
2023-09-27T09:45:58Z   2023-09-27T09:45:58Z   2023-09-27T09:45:58Z
2023-09-27T09:46:02Z   2023-09-27T09:46:02Z   2023-09-27T09:46:02Z
2023-09-27T09:46:04Z   2023-09-27T09:46:04Z   2023-09-27T09:46:04Z
2023-09-27T09:46:08Z   2023-09-27T09:46:08Z   2023-09-27T09:46:08Z
2023-09-27T09:46:09Z   2023-09-27T09:46:09Z   2023-09-27T09:46:09Z
2023-09-27T09:46:12Z   2023-09-27T09:46:12Z   2023-09-27T09:46:12Z
2023-09-27T09:46:15Z   2023-09-27T09:46:15Z   2023-09-27T09:46:15Z
2023-09-27T09:46:19Z   2023-09-27T09:46:19Z   2023-09-27T09:46:19Z
2023-09-27T09:46:23Z   2023-09-27T09:46:23Z   2023-09-27T09:46:23Z
2023-09-27T09:46:25Z   2023-09-27T09:46:25Z   2023-09-27T09:46:25Z
2023-09-27T09:46:30Z   2023-09-27T09:46:30Z   2023-09-27T09:46:30Z
2023-09-27T09:46:30Z   2023-09-27T09:46:30Z   2023-09-27T09:46:30Z
2023-09-27T09:46:30Z   2023-09-27T09:46:30Z   2023-09-27T09:46:30Z
2023-09-27T09:46:30Z   2023-09-27T09:46:30Z   2023-09-27T09:46:30Z
2023-09-27T09:46:33Z   2023-09-27T09:46:33Z   2023-09-27T09:46:33Z
2023-09-27T09:46:34Z   2023-09-27T09:46:34Z   2023-09-27T09:46:34Z
2023-09-27T09:46:36Z   2023-09-27T09:46:36Z   2023-09-27T09:46:36Z
2023-09-27T09:46:38Z   2023-09-27T09:46:38Z   2023-09-27T09:46:38Z
2023-09-27T09:46:38Z   2023-09-27T09:46:38Z   2023-09-27T09:46:38Z
2023-09-27T09:46:40Z   2023-09-27T09:46:40Z   2023-09-27T09:46:40Z
2023-09-27T09:46:41Z   2023-09-27T09:46:41Z   2023-09-27T09:46:41Z
2023-09-27T09:46:44Z   2023-09-27T09:46:44Z   2023-09-27T09:46:44Z
2023-09-27T09:46:47Z   2023-09-27T09:46:47Z   2023-09-27T09:46:47Z
2023-09-27T09:46:51Z   2023-09-27T09:46:51Z   2023-09-27T09:46:51Z
2023-09-27T09:46:54Z   2023-09-27T09:46:54Z   2023-09-27T09:46:54Z
2023-09-27T09:46:57Z   2023-09-27T09:46:57Z   2023-09-27T09:46:57Z
2023-09-27T09:47:02Z   2023-09-27T09:47:02Z   2023-09-27T09:47:02Z
2023-09-27T09:47:05Z   2023-09-27T09:47:05Z   2023-09-27T09:47:05Z
2023-09-27T09:47:08Z   2023-09-27T09:47:08Z   2023-09-27T09:47:08Z
2023-09-27T09:47:12Z   2023-09-27T09:47:12Z   2023-09-27T09:47:12Z
2023-09-27T09:47:16Z   2023-09-27T09:47:16Z   2023-09-27T09:47:16Z
2023-09-27T09:47:18Z   2023-09-27T09:47:18Z   2023-09-27T09:47:18Z
2023-09-27T09:47:23Z   2023-09-27T09:47:23Z   2023-09-27T09:47:23Z
2023-09-27T09:47:26Z   2023-09-27T09:47:26Z   2023-09-27T09:47:26Z
2023-09-27T09:47:29Z   2023-09-27T09:47:29Z   2023-09-27T09:47:29Z
2023-09-27T09:47:33Z   2023-09-27T09:47:33Z   2023-09-27T09:47:33Z
2023-09-27T09:47:37Z   2023-09-27T09:47:37Z   2023-09-27T09:47:37Z
2023-09-27T09:47:39Z   2023-09-27T09:47:39Z   2023-09-27T09:47:39Z
2023-09-27T09:47:40Z   2023-09-27T09:47:40Z   2023-09-27T09:47:40Z
2023-09-27T09:47:44Z   2023-09-27T09:47:44Z   2023-09-27T09:47:44Z
2023-09-27T09:47:47Z   2023-09-27T09:47:47Z   2023-09-27T09:47:47Z
2023-09-27T09:47:50Z   2023-09-27T09:47:50Z   2023-09-27T09:47:50Z
```

**Screenshots (if applicable):**

**Environment (please complete the following information):**
 - Etcd version/commit ID :
 - Etcd-druid version/commit ID :
 - Cloud Provider [All/AWS/GCS/ABS/Swift/OSS]:

**Anything else we need to know?**:

### PR DESCRIPTION
**Pull request by shreyas-s-rao**
**How to categorize this PR?**

/area quality
/kind bug

**What this PR does / why we need it**:
Custodian controller no longer watches lease objects, but rather does an initial reconciliation on any etcd object that has finished reconciliation, and requeues the event for after `SyncPeriod` interval, as was being done previously as well.

This PR ensures that custodian controller does not update the etcd status too frequently, thus saving hundreds of calls to kube-apiserver every second per seed cluster, not to mention the reduction in number of failed etcd status update calls from etcd controller to update `observedGeneration` and `lastError` information.

Additionally, the predicate `EtcdReconciliationFinished` has been modified to check equality of `status.ObservedGeneration` and `metadata.Generation`, rather than `status.Ready`.  Reason for this is that reconciliation is technically finished only when etcd reconciler marks the observedGeneration with the generation it "observes", and has nothing to do with whether the etcd cluster is ready or not. 

**Which issue(s) this PR fixes**:
Fixes #683 

**Special notes for your reviewer**:
/invite @unmarshall @seshachalam-yv 
/assign @unmarshall @seshachalam-yv 

**Release note**:

```bugfix operator
Custodian controller no longer watches leases owned by the etcd resources, thus reducing frequency of etcd status updates and now honouring `custodian-sync-period` value.
```
```noteworthy operator
`custodian-sync-period` value is set to `15s` in the Helm chart for etcd-druid.
```

### CODE REVIEW

File: controllers/custodian/config.go [hunk 1]
```diff
@@ -25,11 +25,12 @@ import (
 const (
 	workersFlagName                     = "custodian-workers"
 	syncPeriodFlagName                  = "custodian-sync-period"
+	requeueIntervalFlagName             = "custodian-requeue-interval"
```
Comment (unmarshall) [inline controllers/custodian/config.go:28]: This is leaking implementation details to the API. Custodian is the name of an internal controller which could change in future and therefore having that as part of an API should be avoided. We have made that mistake in the past and we should not repeat that now.

File: controllers/custodian/config.go [hunk 2]
```diff
@@ -39,7 +40,11 @@ type Config struct {
 	// Workers denotes the number of worker threads for the custodian controller.
 	Workers int
 	// SyncPeriod is the duration after which re-enqueuing happens.
+	// Deprecated: this field will be removed in the future. Please use RequeueInterval instead.
+	// TODO (shreyas-s-rao): remove this in druid v0.22
 	SyncPeriod time.Duration
+	// RequeueInterval is the interval for custodian controller to requeue reconciliations.
+	RequeueInterval time.Duration
```
Comment (unmarshall) [inline controllers/custodian/config.go:47]: I would recommend that we keep `SyncPeriod` for now and not introduce anything else for the moment. We need to look at what we expose carefully and we can decide when we do v1beta1 of the API. Both `SyncPeriod` and `RequeueInterval` fields are very generic and do not tell much on what they will be used for. One needs to read the comment to understand what it means.

In this PR let us just resolve one bug and be done with it.

File: pkg/predicate/predicate.go [hunk 3]
```diff
@@ -23,7 +23,6 @@ import (
 	coordinationv1 "k8s.io/api/coordination/v1"
 	apiequality "k8s.io/apimachinery/pkg/api/equality"
 	"k8s.io/apimachinery/pkg/runtime"
-	"k8s.io/utils/pointer"
```
Comment (unmarshall) [inline pkg/predicate/predicate.go:26]: Can we move this entire package inside controllers? predicate.go is only used inside controllers and nowhere else.

File: pkg/predicate/predicate.go [hunk 4]
```diff
@@ -143,43 +142,33 @@ func LeaseHolderIdentityChange() predicate.Predicate {
...
-// EtcdReconciliationFinished is a predicate to use for etcd resources whose reconciliation is finished.
+// EtcdReconciliationFinished is a predicate to use for etcd resources whose reconciliation has finished.
 func EtcdReconciliationFinished(ignoreOperationAnnotation bool) predicate.Predicate {
 	reconciliationFinished := func(obj client.Object) bool {
 		etcd, ok := obj.(*druidv1alpha1.Etcd)
 		if !ok {
 			return false
 		}
 
-		if ignoreOperationAnnotation {
```
Comment (unmarshall) [inline pkg/predicate/predicate.go:154]: This could have been concisely done as:
```go
	reconciliationFinished := func(obj client.Object) bool {
		etcd, ok := obj.(*druidv1alpha1.Etcd)
		if !ok {
			return false
		}
		reconcilePending := etcd.Status.ObservedGeneration == nil || 
			!hasOperationAnnotation(etcd) && *etcd.Status.ObservedGeneration != etcd.Generation
		return !reconcilePending
	}

```

File: controllers/custodian/config.go (hunk 1 above)
Comment (shreyas-s-rao) [reply controllers/custodian/config.go:28]: Sure. Do you think `etcd-status-update-interval` is a better flag name? It talks about exactly what it does, without any controller implementation details. In that case, we can go ahead and introduce it, and phase out `custodian-sync-period`. WDYT?

File: pkg/predicate/predicate.go (hunk 3 above)
Comment (shreyas-s-rao) [reply pkg/predicate/predicate.go:26]: Sure, I'll do that

File: pkg/predicate/predicate.go (hunk 4 above)
Comment (shreyas-s-rao) [reply pkg/predicate/predicate.go:154]: Agreed that we need a nil check for `etcd.Status.ObservedGeneration` - thanks for pointing it out. I'll add that check.

For the rest of it though, we still need to check whether `ignoreOperationAnnotation` is set to true or false, because it's a configurable flag which users can set to dictate whether druid should ignore the operation annotation (`gardener.cloud/operation`) or respect it. If respected, then the only way to trigger a reconciliation on the etcd is to set the annotation on the etcd resource.

So we still need to check `ignoreOperationAnnotation` and then compute the remaining condition.

File: controllers/custodian/config.go (hunk 1 above)
Comment (unmarshall) [reply controllers/custodian/config.go:28]: yes we can do that but in v1beta1 we will be renaming `Etcd` to `EtcdCluster` so the status update will be for the `EtcdCluster` and not for `Etcd`. I would leave it to you, if you are willing to change this 2 times then please go ahead. Today we have other flags as well like `custodian-workers` as well. We can change all of that in one go when doing the v1beta1 changes to the API. Till then my recommendation would be keep changes in this PR small and only make changes that are essential.

File: pkg/predicate/predicate.go (hunk 4 above)
Comment (unmarshall) [reply pkg/predicate/predicate.go:154]: Ok

**Comment by shreyas-s-rao** [comment]
@unmarshall thanks for your comments. I have addressed them. PTAL

**Review by unmarshall — APPROVED** [review]
/lgtm

**Review by seshachalam-yv — APPROVED** [review]
Thanks @shreyas-s-rao Nice Fix
Saving a lot KAPI calls 🚀 
/lgtm
