### PR TITLE
Fix integration tests by ensuring necessary pods are created

### LINKED ISSUE #831: [Flaky Test] FLAKING Controller/suite
/area testing
/kind flake

**Which test(s)/suite(s) are flaking**:
This [integration test](https://github.com/gardener/etcd-druid/blob/hotfix-v0.22/test/integration/controllers/etcd/reconciler_test.go#L118) is constantly failing in our CI pipeline. I also tried locally but still fails.
```
• [FAILED] [366.511 seconds]
Etcd Controller when adding etcd resources [It] should create and adopt statefulset
```

**CI link**:
https://concourse.ci.gardener.cloud/teams/gardener/pipelines/etcd-druid-hotfix-v0.22/jobs/hotfix-v0.22-release-job/builds/9

**Reason for failure**:
It fails may due to timeout but not sure though
```
  [FAILED] Timed out after 300.000s.
  Expected
      <*bool | 0x0>: nil
  to equal
      <*bool | 0x14000435af8>: true
  In [It] at: ~/go/src/druid_forked/etcd-druid/test/integration/controllers/etcd/reconciler_test.go:136 @ 07/17/24 12:49:23.085

  Full Stack Trace
```

**Anything else we need to know**:
This flaky integration tests have been removed from master branch (may be it removed by PR #777 ) but it still present in branch `hotfix-0.22`   

cc @ashwani2k

### PR DESCRIPTION
**Pull request by seshachalam-yv**
**How to categorize this PR?**

/area testing
/kind bug

**What this PR does / why we need it**:

This PR fixes integration test failures observed after merging PR [#804](https://github.com/gardener/etcd-druid/pull/804), which added new Kubernetes-recommended labels to etcd pods. The existing tests failed because they expected these pods to be present to [verify the labels](https://github.com/gardener/etcd-druid/blob/876927637414906e86ad3f798de6641e8713d975/pkg/component/etcd/statefulset/statefulset.go#L290-L308), but the pods were not created in the test environment. This PR resolves the issue by ensuring that the necessary StatefulSet pods are created and subsequently cleaned up within the integration tests.

**Which issue(s) this PR fixes**:
Fixes #831

**Special notes for your reviewer**:

**Release note**:

```bugfix operator
Fixes integration test failures by ensuring necessary StatefulSet pods are created and deleted appropriately during tests to align with updates made in PR [#804](https://github.com/gardener/etcd-druid/pull/804).
```

### CODE REVIEW

**Review by unmarshall — APPROVED** [review]
/lgtm

**Review by ishan16696 — APPROVED** [review]
LGTM!!

File: test/integration/controllers/etcd/reconciler_test.go [hunk 1]
```diff
@@ -1671,3 +1677,65 @@ var _ = Describe("buildPredicate", func() {
 		)
 	})
 })
+
+func createStsPods(ctx context.Context, cl client.Client, sts *appsv1.StatefulSet) {
```
Comment (shreyas-s-rao) [inline test/integration/controllers/etcd/reconciler_test.go:1681]: Please move this to `test/utils` package, similar to the sts helper functions.

File: test/integration/controllers/etcd/reconciler_test.go [hunk 2]
```diff
@@ -1671,3 +1677,65 @@ var _ = Describe("buildPredicate", func() {
...
+			{
+				Type:   corev1.PodReady,
+				Status: corev1.ConditionTrue,
+			},
+		}
+		ExpectWithOffset(1, cl.Status().Update(ctx, pod)).To(Succeed())
+	}
+}
+
+func deleteStsPods(ctx context.Context, cl client.Client, sts *appsv1.StatefulSet) {
```
Comment (shreyas-s-rao) [inline test/integration/controllers/etcd/reconciler_test.go:1729]: Same as above.

**Review by shreyas-s-rao — CHANGES_REQUESTED** [review]
@seshachalam-yv thanks for the fix. Please address the review comments. Other than that, LGTM 👍

File: test/integration/controllers/etcd/reconciler_test.go (hunk 1 above)
Comment (seshachalam-yv) [reply test/integration/controllers/etcd/reconciler_test.go]: Fixed as part of https://github.com/gardener/etcd-druid/pull/839/commits/8f6b8a607574f2dbd35ef3e2e1f7915c92c2b46d

**Review by shreyas-s-rao — APPROVED** [review]
/lgtm
